from enum import Enum


class SquaresEval(Enum):
    """
    Enum containing hardcoded squares values for pieces
    """
    LEVEL_0: int = -10
    LEVEL_1: int = -5
    LEVEL_2: int = 2
    LEVEL_3: int = 5
    LEVEL_4: int = 7
    LEVEL_5: int = 10
    LEVEL_6: int = 15

    QUEEN: list[int] = [
        LEVEL_0, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_0,
        LEVEL_2, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_2,
        LEVEL_2, LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4, LEVEL_2,
        LEVEL_3, LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4, LEVEL_3,
        LEVEL_3, LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4, LEVEL_3,
        LEVEL_2, LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4, LEVEL_2,
        LEVEL_2, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_2,
        LEVEL_0, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_0
    ]

    KNIGHT: list[int] = [
        LEVEL_0, LEVEL_1, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_1, LEVEL_0,
        LEVEL_1, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_1,
        LEVEL_2, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_2,
        LEVEL_2, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_2,
        LEVEL_2, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_2,
        LEVEL_2, LEVEL_4, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_4, LEVEL_2,
        LEVEL_1, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_1,
        LEVEL_0, LEVEL_1, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_1, LEVEL_0
    ]

    PLAYER_ROOK: list[int] = [
        LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3,
        LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_2, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_2, LEVEL_2
    ]

    ENGINE_ROOK: list[int] = [
        LEVEL_2, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_2, LEVEL_2,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_0, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_2, LEVEL_0,
        LEVEL_4, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_6, LEVEL_4,
        LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3
    ]

    PLAYER_KING: list[int] = [
        LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1,
        LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1,
        LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_2,
        LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_2,
        LEVEL_3, LEVEL_2, LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_2, LEVEL_2, LEVEL_3,
        LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4,
        LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_4,
        LEVEL_4, LEVEL_6, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_6, LEVEL_4
    ]

    ENGINE_KING: list[int] = [
        LEVEL_4, LEVEL_6, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_6, LEVEL_4,
        LEVEL_4, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_4,
        LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4,
        LEVEL_3, LEVEL_2, LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_2, LEVEL_2, LEVEL_3,
        LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_2,
        LEVEL_2, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_2,
        LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1,
        LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0, LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1
    ]

    PLAYER_BISHOP: list[int] = [
        LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0,
        LEVEL_1, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_5, LEVEL_4, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_5, LEVEL_5, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_6, LEVEL_5, LEVEL_5, LEVEL_6, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_1,
        LEVEL_3, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_3
    ]

    ENGINE_BISHOP: list[int] = [
        LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0,
        LEVEL_1, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_5, LEVEL_4, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_5, LEVEL_5, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_6, LEVEL_5, LEVEL_5, LEVEL_6, LEVEL_3, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_3, LEVEL_4, LEVEL_1,
        LEVEL_3, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_3
    ]

    PLAYER_PAWN: list[int] = [
        LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_6, LEVEL_5, LEVEL_5, LEVEL_6, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_1,
        LEVEL_1, LEVEL_5, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_5, LEVEL_1,
        LEVEL_4, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_4
    ]

    ENGINE_PAWN: list[int] = [
        LEVEL_4, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_4,
        LEVEL_1, LEVEL_5, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_5, LEVEL_1,
        LEVEL_1, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_5, LEVEL_1,
        LEVEL_1, LEVEL_3, LEVEL_6, LEVEL_5, LEVEL_5, LEVEL_6, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_6, LEVEL_5, LEVEL_4, LEVEL_1,
        LEVEL_1, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_4, LEVEL_1,
        LEVEL_0, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_1, LEVEL_0
    ]
