from PyQt5 import QtCore, QtGui, QtWidgets


class GameWindowUi(object):
    def setup_ui(self, game_window):
        game_window.setObjectName("game_window")
        game_window.resize(1300, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/resources/images/chess_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        game_window.setWindowIcon(icon)
        game_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.__side_bar = QtWidgets.QFrame(game_window)
        self.__side_bar.setGeometry(QtCore.QRect(0, 0, 91, 721))
        self.__side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__side_bar.setObjectName("__side_bar")

        self.vertical_layout = QtWidgets.QVBoxLayout(self.__side_bar)
        self.vertical_layout.setContentsMargins(9, -1, -1, -1)
        self.vertical_layout.setObjectName("vertical_layout")
        self.__play_frame = QtWidgets.QFrame(self.__side_bar)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.__play_frame.sizePolicy().hasHeightForWidth())

        self.__play_frame.setSizePolicy(sizePolicy)
        self.__play_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.__play_frame.setMaximumSize(QtCore.QSize(70, 70))
        self.__play_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__play_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__play_frame.setObjectName("__play_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.__play_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.__play_menu = QtWidgets.QLabel(self.__play_frame)
        self.__play_menu.setMaximumSize(QtCore.QSize(60, 60))
        self.__play_menu.setText("")
        self.__play_menu.setPixmap(QtGui.QPixmap("src/resources/images/play.svg"))
        self.__play_menu.setScaledContents(True)
        self.__play_menu.setObjectName("__play_menu")
        self.horizontalLayout.addWidget(self.__play_menu)
        self.vertical_layout.addWidget(self.__play_frame)

        self.__analysis_frame = QtWidgets.QFrame(self.__side_bar)
        self.__analysis_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.__analysis_frame.setMaximumSize(QtCore.QSize(70, 70))
        self.__analysis_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__analysis_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__analysis_frame.setObjectName("__analysis_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.__analysis_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.__analysis_menu = QtWidgets.QLabel(self.__analysis_frame)
        self.__analysis_menu.setMaximumSize(QtCore.QSize(60, 60))
        self.__analysis_menu.setText("")
        self.__analysis_menu.setPixmap(QtGui.QPixmap("src/resources/images/analysis.svg"))
        self.__analysis_menu.setScaledContents(True)
        self.__analysis_menu.setObjectName("__analysis_menu")
        self.horizontalLayout_2.addWidget(self.__analysis_menu)
        self.vertical_layout.addWidget(self.__analysis_frame)

        self.__players_frame = QtWidgets.QFrame(self.__side_bar)
        self.__players_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.__players_frame.setMaximumSize(QtCore.QSize(70, 70))
        self.__players_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__players_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__players_frame.setObjectName("__players_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.__players_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.__players_menu = QtWidgets.QLabel(self.__players_frame)
        self.__players_menu.setMaximumSize(QtCore.QSize(60, 60))
        self.__players_menu.setText("")
        self.__players_menu.setPixmap(QtGui.QPixmap("src/resources/images/players.svg"))
        self.__players_menu.setScaledContents(True)
        self.__players_menu.setObjectName("__players_menu")
        self.horizontalLayout_3.addWidget(self.__players_menu)
        self.vertical_layout.addWidget(self.__players_frame)

        self.__profile_frame = QtWidgets.QFrame(self.__side_bar)
        self.__profile_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.__profile_frame.setMaximumSize(QtCore.QSize(70, 70))
        self.__profile_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__profile_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__profile_frame.setObjectName("__profile_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.__profile_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.__profile_menu = QtWidgets.QLabel(self.__profile_frame)
        self.__profile_menu.setMaximumSize(QtCore.QSize(60, 60))
        self.__profile_menu.setText("")
        self.__profile_menu.setPixmap(QtGui.QPixmap("src/resources/images/profile.svg"))
        self.__profile_menu.setScaledContents(True)
        self.__profile_menu.setObjectName("__profile_menu")
        self.horizontalLayout_4.addWidget(self.__profile_menu)
        self.vertical_layout.addWidget(self.__profile_frame)

        self.__settings_frame = QtWidgets.QFrame(self.__side_bar)
        self.__settings_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.__settings_frame.setMaximumSize(QtCore.QSize(70, 70))
        self.__settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__settings_frame.setObjectName("__settings_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.__settings_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.__settings_menu = QtWidgets.QLabel(self.__settings_frame)
        self.__settings_menu.setMaximumSize(QtCore.QSize(60, 60))
        self.__settings_menu.setText("")
        self.__settings_menu.setPixmap(QtGui.QPixmap("src/resources/images/settings.svg"))
        self.__settings_menu.setScaledContents(True)
        self.__settings_menu.setObjectName("__settings_menu")
        self.horizontalLayout_5.addWidget(self.__settings_menu)

        self.vertical_layout.addWidget(self.__settings_frame)
        self.__right_container = QtWidgets.QFrame(game_window)
        self.__right_container.setGeometry(QtCore.QRect(780, 0, 521, 720))
        self.__right_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__right_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__right_container.setObjectName("__right_container")

        self.__pgn_table = QtWidgets.QTableView(self.__right_container)
        self.__pgn_table.setGeometry(QtCore.QRect(20, 80, 491, 481))
        self.__pgn_table.setObjectName("__pgn_table")

        self.__button_frame = QtWidgets.QFrame(self.__right_container)
        self.__button_frame.setGeometry(QtCore.QRect(10, 560, 511, 101))
        self.__button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__button_frame.setObjectName("__button_frame")
        self.horizontal_layout = QtWidgets.QHBoxLayout(self.__button_frame)

        self.horizontal_layout.setObjectName("horizontal_layout")
        self.__new_game_button = QtWidgets.QPushButton(self.__button_frame)
        self.__new_game_button.setMinimumSize(QtCore.QSize(111, 61))
        self.__new_game_button.setObjectName("__new_game_button")
        self.horizontal_layout.addWidget(self.__new_game_button)

        self.__prev_move_button = QtWidgets.QPushButton(self.__button_frame)
        self.__prev_move_button.setMinimumSize(QtCore.QSize(111, 61))
        self.__prev_move_button.setObjectName("__prev_move_button")
        self.horizontal_layout.addWidget(self.__prev_move_button)

        self.__next_move_button = QtWidgets.QPushButton(self.__button_frame)
        self.__next_move_button.setMinimumSize(QtCore.QSize(111, 61))
        self.__next_move_button.setObjectName("__next_move_button")
        self.horizontal_layout.addWidget(self.__next_move_button)

        self.__analyze_button = QtWidgets.QPushButton(self.__button_frame)
        self.__analyze_button.setMinimumSize(QtCore.QSize(111, 61))
        self.__analyze_button.setObjectName("__analyze_button")
        self.horizontal_layout.addWidget(self.__analyze_button)

        self.__user_frame = QtWidgets.QFrame(game_window)
        self.__user_frame.setGeometry(QtCore.QRect(160, 650, 221, 51))
        self.__user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__user_frame.setObjectName("__user_frame")

        self.__user_icon = QtWidgets.QLabel(self.__user_frame)
        self.__user_icon.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.__user_icon.setText("")
        self.__user_icon.setPixmap(QtGui.QPixmap("src/resources/images/user.png"))
        self.__user_icon.setScaledContents(True)
        self.__user_icon.setObjectName("__user_icon")

        self.__user_name = QtWidgets.QLabel(self.__user_frame)
        self.__user_name.setGeometry(QtCore.QRect(66, 12, 151, 31))
        self.__user_name.setObjectName("__user_name")

        self.__engine_frame = QtWidgets.QFrame(game_window)
        self.__engine_frame.setGeometry(QtCore.QRect(150, 20, 221, 51))
        self.__engine_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__engine_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__engine_frame.setObjectName("__engine_frame")

        self.__engine_icon = QtWidgets.QLabel(self.__engine_frame)
        self.__engine_icon.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.__engine_icon.setText("")
        self.__engine_icon.setPixmap(QtGui.QPixmap("src/resources/images/engine.svg"))
        self.__engine_icon.setScaledContents(True)
        self.__engine_icon.setObjectName("__engine_icon")

        self.__engine_name = QtWidgets.QLabel(self.__engine_frame)
        self.__engine_name.setGeometry(QtCore.QRect(66, 12, 151, 31))
        self.__engine_name.setObjectName("__engine_name")

        self.retranslate_ui(game_window)
        QtCore.QMetaObject.connectSlotsByName(game_window)

    def retranslate_ui(self, game_window):
        _translate = QtCore.QCoreApplication.translate
        game_window.setWindowTitle(_translate("game_window", "Chess Engine"))
        self.__new_game_button.setText(_translate("game_window", "New Game"))
        self.__prev_move_button.setText(_translate("game_window", "<"))
        self.__next_move_button.setText(_translate("game_window", ">"))
        self.__analyze_button.setText(_translate("game_window", "Analyze"))
        self.__user_name.setText(_translate("game_window", "User"))
        self.__engine_name.setText(_translate("game_window", "Engine"))
